<?php echo $this->doctype(); $_SESSION['base_lang'] = 0?> <!-- // Reset language when refreshing a page (0 = English) -->

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle(' - Cases')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- CSS -->
    <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/flag-icon.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', ['conditional' => 'lt IE 9'])
        ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', ['conditional' => 'lt IE 9']); ?>

</head>
<body>
<div id="wrapper">
    <div id="header">
        <div class="top-line">&nbsp;</div>
        <div class="top">
            <div class="row">
                <div class="col-lg-1"></div> <!-- // Diagnostic logo instead of Cases logo -->
                <div class="col-lg-3"><a href="http://www.cases.lu"><img
                                src="/img/logo_diagnostic.jpg"
                                border="0"
				width="220"
				height="80"></a></div>
                <div class="col-lg-4 text-center text-uppercase"><h1><?= $this->translate('__diagnostic') ?> CASES</h1></div>
                <div class="col-lg-3 text-right">
                    <br />
                    <?php
		    // Determine which button is active related to the active language //
                    $locale = $this->plugin('translate')->getTranslator()->getLocale();
		    $location_lang = "/var/www/diagnostic/language/languages.txt";
                    $file_lang = fopen($location_lang, "r");
                    $i = 1;
                    $_SESSION['nb_lang'] = 0;
                    while (!feof($file_lang)) {
       	                $temp_lang = fgets($file_lang, 4096);
                        $_SESSION['class_lang'][$i] = '';
                        if ($locale.PHP_EOL == $temp_lang) {
                            $_SESSION['class_lang'][$i] = 'btn-info';
                        }
                        $i++;
                        $_SESSION['nb_lang']++;
                    }
                    fclose($file_lang);
                    // *************************************************************** //
                    ?>
                    <table width="100%">
                        <tr>
                            <td align="right">
                                <?php
                                $container = new \Zend\Session\Container('user');
                                if (($container->offsetExists('admin')) && (!is_null($container->admin)) && ($container->admin == 1)) {
                                    if ($this->url() == '/admin') {
                                        ?>
                                        <a href="<?= $this->url('diagnostic', ['action' => 'diagnostic']); ?>"
                                           class="btn btn-success"><?= $this->translate('__diagnostic') ?></a>
                                        <?php
                                    } else {
                                        ?>
                                        <a href="<?= $this->url('admin', []); ?>"
                                           class="btn btn-primary"><?= $this->translate('__admin') ?></a>
                                        <?php
                                    }
                                }
                                if (($container->offsetExists('email')) || (!is_null($container->email))) {
                                    ?>
                                    <a href="<?= $this->url('diagnostic', ['action' => 'logout']); ?>"
                                       class="btn btn-danger"><?= $this->translate('__logout') ?></a>
                                    <?php
                                }
                                ?>
			    </td>

			    <?php
                            // Creation language button //
                            $file_lang = fopen($location_lang, "r");
                            for ($i=1; $i<$_SESSION['nb_lang']; $i++) {
                                $temp_lang = fgets($file_lang, 4096);
                            ?>
                                <td width='75'>
                                    <a href="<?php echo $this->url('diagnostic', ['action' => 'language', 'id' => $i]); ?>">
                                        <button type='submit' name='language' value=<?= $temp_lang ?>
                                            class="btn-default btn-blue btn-sm <?php echo $_SESSION['class_lang'][$i] ?>"><span
                                            class='text-uppercase'><span class='flag-icon flag-icon-<?php echo $temp_lang ?>'></span>&nbsp;&nbsp;<?= $temp_lang ?></span>
                                        </button>
                                    </a>
                                </td>
                            <?php
                            }
                            fclose($file_lang);
                            // ************************ //
                            ?>
                        </tr>
                    </table>
            </div>
                <div class="col-lg-1"></div>
            </div>
        </div>

        <div class="legend">
            <div class="col-lg-1">
            </div>
            <div class="col-lg-10 text-left">
                <?php
                $routeMatch = $this->getHelperPluginManager()
                    ->getServiceLocator()
                    ->get('Application')
                    ->getMvcEvent()
                    ->getRouteMatch();
                if ($routeMatch) {
                    $currentModule = $routeMatch->getMatchedRouteName();

                    if ($currentModule == 'admin') {
                        ?>
                        <div id="navbar" class="collapse navbar-collapse">
                            <?= $this->navigation('navigation')
                                ->menu()
                                ->setMinDepth(0)
                                ->setMaxDepth(0)
                                ->setUlClass('nav navbar-nav'); ?>
                        </div>
                        <?php
                    }
                }
                ?>
            </div>
            <div class="col-lg-1"></div>
        </div>

        <br>

        <div>
            <div class="row">
                <div class="col-lg-1"></div>
                <div class="col-lg-10">
                    <?php echo $this->content; ?>
                </div>
                <div class="col-lg-1"></div>
            </div>
        </div>

    </div>
</div>
<br>

<div class="footer">
</div>

<div class="credits-section">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-4">
            <div class="footer-credits"><!-- Footer credits -->
                Diagnostic v1.2 - 2015-2018 &copy; Cases.lu - Tous droits réservés.
            </div>
        </div>
        <div class="col-md-6">
            <div class="footer-credits"><!-- Footer credits -->
                Brought to you by <a href="https://securitymadein.lu/" class="milu-btn"><span
                            style="text-transform:uppercase; color:#fff;">security<span
                                style="color:#00FFF6">made</span>in.<span style="color:#00FFF6">lu</span></span></a>
            </div>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>
</body>

</html>
