<?php
$title = $this->translate('__diagnostic');
$this->headTitle($title);

$form->setAttribute('action', $this->url('diagnostic', ['action' => 'add-question'], ['query' => ['categoryId' => $categoryId, 'id' => $id]]));
$form->prepare();
?>
<div class="row">
    <div class="col-lg-3 text-center"></div>
    <div class="col-lg-6 text-left">
        <h2><?= $this->translate('__add_a_question') ?></h2>
        <br/>
        <?= $this->form()->openTag($form) ?>
        <table class="table table-responsive table-borderless">
            <tr>
                <td><label><?= $this->translate($form->get('question')->getLabel()) ?></label></td>
                <td>
                    <?= $this->formText($form->get('question')) ?>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <?= $this->formElementErrors($form->get('question'), ['class' => 'bg-danger']) ?>
                </td>
            </tr>
            <tr>
                <td><label><?= $this->translate($form->get('help')->getLabel()) ?></label></td>
                <td>
                    <?= $this->formText($form->get('help')) ?>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <?= $this->formElementErrors($form->get('help'), ['class' => 'bg-danger']) ?>
                </td>
            </tr>
            <tr>
                <td><label><?= $this->translate('__threshold_max') ?></label></td>
                <td>
                    <label><?= $this->translate($form->get('threat')->getLabel()) ?></label>
                    <?= $this->formSelect($form->get('threat')) ?>
                    &nbsp; X &nbsp;
                    <label><?= $this->translate($form->get('weight')->getLabel()) ?></label>
                    <?= $this->formSelect($form->get('weight')) ?>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <?= $this->formElementErrors($form->get('threat'), ['class' => 'bg-danger']) ?>
                    <?= $this->formElementErrors($form->get('weight'), ['class' => 'bg-danger']) ?>
                    <?= $this->formSubmit($form->get('submit')) ?>
                </td>
            </tr>
        </table>
        <?= $this->formHidden($form->get('csrf')) ?>
        <?= $this->form()->closeTag() ?>
    </div>
    <div class="col-lg-3 text-center"></div>
</div>
