<?php
$title = $this->translate('__diagnostic');
$this->headTitle($title);

$form->setAttribute('action', $this->url('diagnostic', ['action' => 'new-password'], ['query' => ['token' => $token]]));
$form->prepare();
?>
<br/>

<div class="row">
    <div class="col-lg-12 text-center">
        <h2><?= $this->translate('__new_password') ?></h2>
        <br/>
        <?= $this->form()->openTag($form) ?>
        <table class="table table-responsive table-borderless">
            <tr>
                <td><label><?= $this->translate($form->get('password')->getLabel()) ?></label></td>
                <td><?= $this->formPassword($form->get('password')) ?></td>
            </tr>
            <tr>
                <td colspan="2"><?= $this->formElementErrors($form->get('password'), ['class' => 'bg-danger']) ?></td>
            </tr>
            <tr>
                <td><label><?= $this->translate($form->get('password2')->getLabel()) ?></label></td>
                <td><?= $this->formPassword($form->get('password2')) ?></td>
            </tr>
            <tr>
                <td colspan="2"><?= $this->formElementErrors($form->get('password2'), ['class' => 'bg-danger']) ?></td>
            </tr>
        </table>
        <?= $this->formHidden($form->get('csrf')) ?>
        <?= $this->formSubmit($form->get('submit')) ?></td>
        <?= $this->form()->closeTag() ?>
    </div>
</div>