<?php
$title = $this->translate('__diagnostic');
$this->headTitle($title);

$form->setAttribute('action', $this->url('diagnostic', array('action' => 'password-forgotten')));
$form->prepare();
?>
<br/>

<div class="row">
    <div class="col-lg-2 text-center"></div>
    <div class="col-lg-8 text-center">
        <h2><?= $this->translate('__password_forgotten') ?></h2>
        <br/>
        <?= $this->form()->openTag($form) ?>
        <table class="table table-responsive table-borderless">
            <tr>
                <td><label><?= $this->translate($form->get('email')->getLabel()) ?></label></td>
                <td><?= $this->formText($form->get('email')) ?></td>
            </tr>
            <tr>
                <td colspan="2"><?= $this->formElementErrors($form->get('email'), array('class' => 'bg-danger')) ?></td>
            </tr>
        </table>
        <?= $this->formHidden($form->get('csrf')) ?>
        <?= $this->formSubmit($form->get('submit')) ?></td>
        <?= $this->form()->closeTag() ?>
        <br/><br/>
        <?= $this->translate('__message_password') ?>
    </div>
    <div class="col-lg-2 text-center"></div>
</div>