<?php
$title = $this->translate('__rapport');
$this->headTitle($title);

$jsPercents = [];
$jsCategories = [];
foreach ($totalCategory as $key => $value) {
    $jsPercents[] = $value;
    $jsCategories[] = $this->translate($key);
}

$rgbaColorDangerBorder = 'rgba(228, 185, 185, 1)';
$rgbaColorDanger = 'rgba(242, 222, 222, 1)';
$rgbaColorWarningBorder = 'rgba(247, 236, 181, 1)';
$rgbaColorWarning = 'rgba(252, 248, 227, 1)';
$rgbaColorInfoBorder = 'rgba(175, 217, 238, 1)';
$rgbaColorInfo = 'rgba(217, 237, 247, 1)';
$rgbaColorSuccessBorder = 'rgba(193, 226, 179, 1)';
$rgbaColorSuccess = 'rgba(223, 240, 216, 1)';

switch (true) {
    case ($this->total < 25):
        $totalColor = 'danger';
        $chartColor = $rgbaColorDanger;
        $chartColorBorder = $rgbaColorDangerBorder;
        break;
    case ($this->total < 50):
        $totalColor = 'warning';
        $chartColor = $rgbaColorWarning;
        $chartColorBorder = $rgbaColorWarningBorder;
        break;
    case ($this->total < 75):
        $totalColor = 'info';
        $chartColor = $rgbaColorInfo;
        $chartColorBorder = $rgbaColorInfoBorder;
        break;
    default:
        $totalColor = 'success';
        $chartColor = $rgbaColorSuccess;
        $chartColorBorder = $rgbaColorSuccessBorder;
        break;
}

switch (true) {
    case ($this->totalTarget < 25):
        $chartTargetColor = $rgbaColorDanger;
        $chartTargetColorBorder = $rgbaColorDangerBorder;
        break;
    case ($this->totalTarget < 50):
        if (($this->total >=25 ) && ($this->total < 50)) {
            $chartTargetColor = $rgbaColorDanger;
            $chartTargetColorBorder = $rgbaColorDangerBorder;
        } else {
            $chartTargetColor = $rgbaColorWarning;
            $chartTargetColorBorder = $rgbaColorWarningBorder;
        }
        break;
    case ($this->totalTarget < 75):
        if (($this->total >=50 ) && ($this->total < 75)) {
            $chartTargetColor = $rgbaColorWarning;
            $chartTargetColorBorder = $rgbaColorWarningBorder;
        } else {
            $chartTargetColor = $rgbaColorInfo;
            $chartTargetColorBorder = $rgbaColorInfoBorder;
        }
        break;
    default:
        if (($this->total >=75 )) {
            $chartTargetColor = $rgbaColorInfo;
            $chartTargetColorBorder = $rgbaColorInfoBorder;
        } else {
            $chartTargetColor = $rgbaColorSuccess;
            $chartTargetColorBorder = $rgbaColorSuccessBorder;
        }
        break;
}

echo $this->inlineScript()->prependFile($this->basePath('js/Chart.js-master/Chart.js'));
?>

<style>
    .chart-legend li span{
        display: inline-block;
        width: 12px;
        height: 12px;
        margin-right: 5px;
    }
</style>

<div class="row">
    <div class="col-lg-12 text-center bg-<?= $totalColor ?>">
        <h2><?= ucfirst($this->translate('__results')) ?> : <?php echo $this->escapeHtml($total); ?>/100</h2>
    </div>
</div>

<br />

<div class="row">
    <div class="col-lg-6 text-center" style="background-color: #EEEEEE;">
        <h1><?php echo ucfirst($this->translate($this->escapeHtml('__riks_cartography')));?></h1>
        <div class="row">
            <div class="col-lg-2 text-center"></div>
            <div class="col-lg-8 text-center">
                <canvas id="canvas" width="500" height="400"></canvas>
            </div>
            <div class="col-lg-2 text-center"></div>
         </div>
    </div>
    <div class="col-lg-6 text-center">
        <h1><?php echo ucfirst($this->translate($this->escapeHtml('__categories')));?></h1>
        <table class="table">
            <?php
            foreach ($totalCategory as $key => $value) :
                $valueColor = '';
                if ($value < 25) {
                    $valueColor = 'text-danger';
                }
                if ($value > 75) {
                    $valueColor = 'text-success';
                }
                ?>
                <tr>
                    <td class="text-left <?= $valueColor ?>"><?= $this->translate($this->escapeHtml($key)) ?></td>
                    <td class="text-right <?= $valueColor ?>"><?= (int) $value ?>%</td>
                </tr>
            <?php endforeach; ?>
        </table>
        <center>
            <?php
            $form->setAttribute('action', $this->url('diagnostic', array('action' => 'download')));
            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('radar'));
            echo $this->formHidden($form->get('pie'));
            echo $this->formHidden($form->get('bar'));
            ?>
            <br><br>
            <table style="width: 100%">
                <tr>
                    <?php
                    if ($this->download) {
                        ?>
                        <td align="center">
                            <button type="submit" class="btn btn-warning" style="padding: 7px 70px 7px 70px;">
                                <span class="glyphicon glyphicon-download-alt"></span>&nbsp;<?= $this->translate('__download_delivery') ?>
                            </button>
                        </td>
                        <?php
                    }
                    ?>
                    <td align="center">
                        <a href="<?= $this->url('diagnostic',array('action'=>'diagnostic'));?>" class="btn btn-info" style="padding: 7px 70px 7px 70px;">
                            <span class="glyphicon glyphicon-backward"></span>&nbsp;<?= $this->translate('__back') ?>
                        </a>
                    </td>
                    <td align="center">
                        <a href="<?= $this->url('diagnostic',array('action'=>'index'));?>" class="btn btn-default" style="padding: 7px 70px 7px 70px;">
                            <span class="glyphicon glyphicon-home"></span>&nbsp;<?= $this->translate('__home') ?>
                        </a>
                    </td>
                </tr>
            </table>
            <?php
            echo $this->form()->closeTag();
            ?>
        </center>
    </div>
</div>

<div class="row">
    <div class="col-lg-6 text-center">
        <?php
        if (count($this->recommandations)) {
            echo '<h1>' . ucfirst($this->translate($this->escapeHtml('__recommandations'))) . '</h1>';
            ?>
            <table class="table table-striped table-hover">
                <tr class="info">
                    <th><?= $this->translate('__recommandation'); ?></th>
                    <th><?= $this->translate('__category'); ?></th>
                    <th style="text-align: center"><?= $this->translate('__gravity'); ?></th>
                    <th style="text-align: center" width="100"><?= $this->translate('__goal'); ?></th>
                </tr>
                <?php foreach ($this->recommandations as $recommandation) :
                    if (strlen($recommandation['recommandation'])) {
                        ?>
                        <tr>
                            <td style="text-align: left;"><?= $recommandation['recommandation']; ?></td>
                            <td style="text-align: left;"><?= $this->translate($recommandation['domaine']); ?></td>
                            <td style="text-align: center;"><img src="<?= $recommandation['gravity']; ?>" /></td>
                            <td style="text-align: center;"><img src="<?= $recommandation['maturity'] ?>" />&nbsp;<span class="glyphicon glyphicon-arrow-right"></span>&nbsp;<img src="<?= $recommandation['maturityTarget'] ?>" /></td>
                        </tr>
                        <?php
                    }
                endforeach; ?>
            </table>
            <br />
            <table class="table table-borderless">
                <tr>
                    <th><?= $this->translate('__maturity_levels') ?></th>
                    <th>&nbsp; &nbsp;</th>
                    <th><?= $this->translate('__gravity_levels') ?></th>
                </tr>
                <tr>
                    <td style="vertical-align: top;">
                        <table class="table" style="background-color: lightgrey; border: 1px solid darkgrey; height: 45px;">
                            <tr>
                                <td><img src="/img/mat_none.png" /></td>
                                <td><?= $this->translate('__maturity_none') ?></td>
                                <td><img src="/img/mat_plan.png" /></td>
                                <td><?= $this->translate('__maturity_plan') ?></td>
                                <td><img src="/img/mat_moyen.png" /></td>
                                <td><?= $this->translate('__maturity_medium') ?></td>
                                <td><img src="/img/mat_ok.png" /></td>
                                <td><?= $this->translate('__maturity_ok') ?></td>
                            </tr>
                        </table>
                    </td>
                    <td></td>
                    <td>
                        <table class="table" style="background-color: lightgrey; border: 1px solid darkgrey; height: 45px;">
                            <tr>
                                <td><img src="/img/gravity_1.png" /></td>
                                <td><?= $this->translate('__low') ?></td>
                                <td><img src="/img/gravity_2.png" /></td>
                                <td><?= $this->translate('__medium') ?></td>
                                <td><img src="/img/gravity_3.png" /></td>
                                <td><?= $this->translate('__strong') ?></td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
            <?php
        }
        ?>

    </div>
    <div class="col-lg-6 text-center">

        <h1><?php echo ucfirst($this->translate($this->escapeHtml('__maturity_evolution')));?></h1>
        <div class="row">
            <div class="col-lg-2 text-left"></div>
            <div class="col-lg-8 text-left">
                <br />
                <canvas id="canvas3" width="500" height="300"></canvas>
                <div id="canvas3-legend" class="chart-legend"></div>
            </div>
            <div class="col-lg-2 text-left"></div>
        </div>
        <br />
        <h1><?php echo ucfirst($this->translate($this->escapeHtml('__doughnut_legend')));?></h1>
        <div class="row">
            <div class="col-lg-2 text-left"></div>
            <div class="col-lg-8 text-left">
                <br /><br /><br />
                <div class="row">
                    <div class="col-lg-2 text-left"></div>
                    <div class="col-lg-8 text-left">
                        <canvas id="canvas2" width="100" height="100"></canvas>
                        <div id="canvas2-legend" class="chart-legend" ></div>
                    </div>
                    <div class="col-lg-2 text-left"></div>
                </div>
            </div>
            <div class="col-lg-2 text-left"></div>
        </div>
    </div>
</div>

<div style="width: 100%; height: 100%;">
    <canvas id="myChart" style="width: 100%; height: auto;"></canvas>
</div>
<div id="js-legend" class="chart-legend"></div>

<script>
    //radar chart
    var radarChartData = {
        labels: <?= json_encode($jsCategories) ?>,
        datasets: [
            {
                label: "Cases radar",
                fillColor: "rgba(91, 192, 222, 0.3)",
                strokeColor: "rgba(48, 113, 169, 1)",
                pointColor: "rgba(48, 113, 169, 1)",
                pointStrokeColor: "#fff",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(220,220,220,1)",
                data: <?= json_encode($jsPercents) ?>
            }
        ]
    };

    var myRadarChart = new Chart(document.getElementById("canvas").getContext("2d")).Radar(radarChartData, {
        responsive: false,
        onAnimationComplete : function() {
            document.querySelector('input[name="radar"]').value = myRadarChart.toBase64Image();
        }
    });


    //doughnut chart
    var doughnutChartData =  <?= json_encode($this->categoriesRepartition) ?>;

    var myDoughnutChart = new Chart(document.getElementById("canvas2").getContext("2d")).Doughnut(doughnutChartData,{
        responsive: true,
        legendTemplate : "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<segments.length; i++){%><li><span style=\"background-color:<%=segments[i].fillColor%>\"></span><%if(segments[i].label){%><%=segments[i].label%><%}%></li><%}%></ul>",
        onAnimationComplete : function() {
            document.querySelector('input[name="pie"]').value = myDoughnutChart.toBase64Image();
        }
    });

    document.getElementById('canvas2-legend').innerHTML = myDoughnutChart.generateLegend();


    //bar chart
    var barChartData = {
        labels: [''],
        datasets: [
            {
                label: "<?= $this->translate('__actual') ?>",
                fillColor: "<?= $chartColor ?>",
                strokeColor: "<?= $chartColorBorder ?>",
                highlightFill: "rgba(220,220,220,0.75)",
                highlightStroke: "rgba(220,220,220,1)",
                data: [<?= $this->total ?>]
            },
            {
                label: "<?= $this->translate('__target') ?>",
                fillColor: "<?= $chartTargetColor ?>",
                strokeColor: "<?= $chartTargetColorBorder ?>",
                highlightFill: "rgba(151,187,205,0.75)",
                highlightStroke: "rgba(151,187,205,1)",
                data: [<?= $this->totalTarget ?>]
            }
        ]
    };

    var myBarChart = new Chart(document.getElementById("canvas3").getContext("2d")).Bar(barChartData, {
        responsive: true,
        tooltipTemplate: "<%= value %>%",
        onAnimationComplete : function() {
            document.querySelector('input[name="bar"]').value = myBarChart.toBase64Image();
        }
    });

    document.getElementById('canvas3-legend').innerHTML = myBarChart.generateLegend();

</script>
