<?php use Zend\Form\Element;

$title = $this->translate('__category');
$this->headTitle($title);

$this->form->setAttribute('action', $this->url('admin', ['action' => 'add-category']));
$this->form->prepare(); ?>

<div class="row">
    <div class="col-lg-3 text-center"></div>
    <div class="col-lg-6 text-left">
        <h2><?= $this->translate('__add_a_category') ?></h2>
        <br />

        <?= $this->form()->openTag($form) ?>

        <table class="table table-responsive table-borderless">
            <tr>
                <td><label><?= $this->translate($form->get('translation_key')->getLabel()) ?></label></td>
                <td>
                    <?= $this->formText($form->get('translation_key')->setValue('__category' . $_SESSION['nb_categories'])) ?>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <?= $this->formElementErrors($form->get('translation_key'), ['class' => 'bg-danger']) ?>
                    <!-- // Display error if the translation key already exist -->
                    <?php if($_SESSION['erreur_exist'] == 1){ echo "<ul class='bg-danger'> <li>" . $this->translate('__error_exist'). "</li></ul>"; } ?>
                </td>
            </tr>
            <!-- // Translations label and form-text -->
	    <?php
            $file = fopen("/var/www/diagnostic/language/languages.txt", "r");
            for($i=1; $i<$_SESSION['nb_lang']; $i++) {
                $temp = fgets($file, 4096);

                // Creation translation form
                $translation = new Element('translation_' . substr($temp, 0, -1)); // substr is for deleting the /n
                $translation->setLabel('__translation');
                $translation->setAttributes([
                    'type'  => 'text',
                    'class' => 'form-control'
                ]);
                $form->add($translation);
                ?>
                <tr>
                    <td><label><?= $this->translate($form->get('translation_' . substr($temp, 0, -1))->getLabel()) ?></label>&nbsp;<span class="flag-icon flag-icon-<?= $temp ?>"></span></td>
                    <td>
                        <?= $this->formText($form->get('translation_' . substr($temp, 0, -1))) ?>
                    </td>
                </tr>
            <?php
            }
            fclose($file);
            ?>
            <tr>
                <td colspan="2">
                    <?= $this->formSubmit($form->get('submit')) ?>
                </td>
            </tr>
        </table>
        <?= $this->formHidden($form->get('csrf')) ?>
        <?= $this->form()->closeTag() ?>
    </div>
    <div class="col-lg-3 text-center"></div> </div>
