<?php
$title = $this->translate('__diagnostic');
$this->headTitle($title);

$this->form->setAttribute('action', $this->url('admin', ['action' => 'add-question']));
$this->form->prepare();
?>
<div class="row">
    <div class="col-lg-3 text-center"></div>
    <div class="col-lg-6 text-left">
        <h2><?= $this->translate('__add_a_question') ?></h2>
        <br />
        <?= $this->form()->openTag($form) ?>
        <table class="table table-responsive table-borderless">
            <tr>
                <td><label><?= $this->translate($form->get('translation_key')->getLabel()) ?></label></td>
                <td>
                    <?= $this->formText($form->get('translation_key')) ?>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <?= $this->formElementErrors($form->get('translation_key'), array('class' => 'bg-danger')) ?>
                </td>
            </tr>
            <tr>
                <td><label><?= $this->translate($form->get('category_id')->getLabel()) ?></label></td>
                <td>
                    <?= $this->formSelect($form->get('category_id')) ?>
                </td>
            </tr>
            <tr>
                <td><label><?= $this->translate($form->get('threshold')->getLabel()) ?></label></td>
                <td>
                    <?= $this->formSelect($form->get('threshold')) ?>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <?= $this->formElementErrors($form->get('category_id'), array('class' => 'bg-danger')) ?>
                    <?= $this->formElementErrors($form->get('threshold'), array('class' => 'bg-danger')) ?>
                    <?= $this->formSubmit($form->get('submit')) ?>
                </td>
            </tr>
        </table>
        <?= $this->formHidden($form->get('csrf')) ?>
        <?= $this->form()->closeTag() ?>
    </div>
    <div class="col-lg-3 text-center"></div>
</div>