<?php
$title = $this->translate('__categories');
$this->headTitle($title);
$_SESSION['category_max'] = 1; // Count number of category

$this->form->setAttribute('action', $this->url('admin', ['action' => 'categories']));
$this->form->prepare();

?>

<?= $this->form()->openTag($form) ?>

<!-- // Display confirmation if you want to delete a category. -->
<script>var delete_category = <?php echo json_encode($this->translate('__delete_category')) ?></script>

<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8 text-left">
        <h2><?= $this->translate('__categories') ?></h2>
        <br />

        <!-- // Upload part -->
        <div class="col-lg-4 text-left"><?= $this->formFile($form->get('file')); ?></div>
        <?= $this->formSubmit($form->get('submit_file')); ?>
        <?= $this->formSubmit($form->get('submit')); ?>
        <br />
        <div class="col-lg-4 text-left">
            <?php if($error_upload == 1){ echo "<ul class='bg-danger'> <li>" . $this->translate('__error_file'). "</li></ul>"; }
            if($error_id == 1){ echo "<ul class='bg-danger'> <li>" . $this->translate('__error_id'). "</li></ul>"; } ?>
        </div>

        <br />
        <br />
        <br />

        <?php
        $urlAdd = $this->url('admin', ['action' => 'add-category']);
        ?>
        <center>
            <a href="<?= $urlAdd ?>" style="color: #DF1D31; font-weight: bold;"><span
                        class="glyphicon glyphicon-plus-sign"></span> <?= $this->translate('__add_a_category') ?></a>
        </center>
        <br/>
        <table class="table">
            <tr>
                <th style="text-align: center"><?= $this->translate('__category'); ?></th>
                <th><?= $this->translate('__translation_key'); ?></th>
                <th style="text-align: center;"><?= $this->translate('__action'); ?></th>
            </tr>
            <?php
            foreach ($categories as $category) :
                if (substr($category->getTranslationKey(), 10) > $_SESSION['category_max']) {$_SESSION['category_max'] = substr($category->getTranslationKey(), 10);}
                $urlModify = $this->url('admin', ['action' => 'modify-category', 'id' => $category->getId()]);
                $urlDelete = $this->url('admin', ['action' => 'delete-category', 'id' => $category->getId()]);
            ?>
                <tr>
                    <td align="center"><?= $this->translate($category->getTranslationKey()); ?></td>
                    <td><?= $category->getTranslationKey(); ?></td>
                    <td align="center">
                        <a href="<?= $urlModify ?>"><span class="glyphicon glyphicon-pencil"></span></a>
                        &nbsp;&nbsp;
                        <a href="<?= $urlDelete ?>" onclick='return confirm(delete_category)'><span class="glyphicon glyphicon-remove"></span></a>
                    </td>
                </tr>
            <?php
            endforeach;
            ?>
        </table>
    </div>
</div>

<?= $this->form()->closeTag() ?>
