<?php use Zend\Form\Element; use Zend\Form\Form;

$title = $this->translate('__languages');
$this->headTitle($title);

$this->form->setAttribute('action', $this->url('admin', ['action' => 'languages']));
$this->form->prepare();

// Retrieve number of questions
$_SESSION['nb_questions'] = 1;
foreach ($questions as $question) :
    $_SESSION['nb_questions']++;
endforeach;

?>

<script>
    var delete_lang = <?php echo json_encode($this->translate('__delete_lang')) ?>;
    var delete_trans = <?php echo json_encode($this->translate('__delete_trans')) ?>;
</script>

<div class="row">

    <?= $this->form()->openTag($form) ?>
    <span style="float:right"><?= $this->translate($form->get('add_language')->getLabel()) ?>
    <?= $this->formSelect($form->get('add_language')) ?>
    <?= $this->formSubmit($form->get('submit_lang_add')) ?>
    <?= $this->formSubmit($form->get('submit_lang_del')->setAttribute('onClick', 'return confirm(delete_lang)')) ?>
    <?php if($lang_exist == 1){ echo "<ul class='bg-danger'> <li>" . $this->translate('__error_exist2'). "</li></ul>"; } ?>
    <?php if($lang_exist2 == 2){ echo "<ul class='bg-danger'> <li>" . $this->translate('__error_exist3'). "</li></ul>"; } ?>
    <?php if($lang_exist3 == 1){ echo "<ul class='bg-danger'> <li>" . $this->translate('__error_exist4'). "</li></ul>"; } ?></span>

    <h2><?= $this->translate('__languages') ?></h2>

    <br />
    <br />

    <table class="table table-responsive">

	<tr>
            <th style="text-align: center"><?= $this->translate('__translation_key'); ?></th>
            <th style="text-align: center;"><?= $this->translate('__translation'); ?></th>
	    <th style="text-align: center;"><?= $this->translate($form->get('language_ref')->getLabel()); ?> &nbsp; <?= $this->formSelect($form->get('language_ref')) ?> &nbsp; <?= $this->formSubmit($form->get('submit_lang_ref')) ?></th>
	    <th style="text-align: center;"><?= $this->translate('__action'); ?></th>
        </tr>

	<?php

	$file_lang = fopen('/var/www/diagnostic/language/languages.txt', 'r');
	for ($i=1; $i<$_SESSION['nb_lang']; $i++) {
	    $temp_lang = fgets($file_lang, 4096);

	    if ($this->plugin('translate')->getTranslator()->getLocale() == substr($temp_lang, 0, -1)) {

	        $_SESSION['lang'] = substr($temp_lang, 0, -1);

		$n = 3; $j = 2; $k = 1; $z = 1;

		$file = fopen('/var/www/diagnostic/language/' . substr($temp_lang, 0, -1) . '.po', 'r');
		// Go to the first msgid in the po file
	        while (!feof($file)) {
		    $temp = fgets($file, 4096);
		    if (substr($temp, 7, -2) == '__question' . ($_SESSION['nb_questions']-1) . 'help') {$temp = fgets($file, 4096); $temp = fgets($file, 4096); break;}
		}
		while (!feof($file)) {
	    	    $temp = fgets($file, 4096);

		    // Creation translation form
       		    $translation = new Element('translation' . $k);
       	   	    $translation->setAttributes([
                        'type'  => 'text',
                        'class' => 'form-control'
                    ]);
                    $form->add($translation);

		    // Creation translation form
	            $submit = new Element('mod' . $k);
      		    $submit->setAttributes([
                        'type'  => 'submit',
                        'class' => 'btn btn-success'
                    ]);
                    $form->add($submit);

	    	    // Creation translation form
            	    $submit = new Element('del' . $k);
            	    $submit->setAttributes([
                        'type'  => 'submit',
                	'class' => 'btn btn-success'
            	    ]);
            	    $form->add($submit);

   	    	    if($n==3){
			echo "<tr><td class=col-lg-2 style=text-align:center>";
			echo $_SESSION['key_' . substr($temp_lang, 0, -1)][$k]=substr($temp, 7, -2);
			echo "</td>";
			$n=0;
		    }
	    	    if($j==3){
			echo "<td class=col-lg-5>";
			echo $this->formText($form->get('translation'.$k)->setValue(substr($temp, 8, -2)));
			echo '</td>';
			echo '<td id="' . $z . '" style=text-align:center; class=col-lg-3>';
	    	    	echo '</td>';
			echo '<td style=text-align:center>';
			echo $this->formSubmit($form->get('mod' . $k)->setValue($this->translate('__modify')));
			echo "&nbsp;&nbsp;";
			echo $this->formSubmit($form->get('del'.$k)->setValue($this->translate('__delete'))->setAttribute('onClick', 'return confirm(delete_trans)'));
			echo "</td></div></tr>";
			$k++;
			$z++;
			$j=0;
		    }
		    $n++;
	            $j++;
	        }
	        fclose($file);
	    }
        }
	fclose($file_lang);

	$file_lang = fopen('/var/www/diagnostic/language/languages.txt', 'r');
	for ($i=1; $i<$_SESSION['nb_lang']; $i++) {
	    $temp_lang = fgets($file_lang, 4096);

	    if ($_SESSION['change_language'] == substr($temp_lang, 0, -1)) {

		$j = 2; $z = 1;

		$file = fopen('/var/www/diagnostic/language/' . substr($temp_lang, 0, -1) . '.po', 'r');
		// Go to the first msgid in the po file
	        while (!feof($file)) {
		    $temp = fgets($file, 4096);
		    if (substr($temp, 7, -2) == '__question' . ($_SESSION['nb_questions']-1) . 'help') {$temp = fgets($file, 4096); $temp = fgets($file, 4096); break;}
		}
		while (!feof($file)) {
	    	    $temp = fgets($file, 4096);

		    if($j==3){
		    	?>
		    	<script>
		            document.getElementById('<?php echo $z ?>').innerHTML = "<?= htmlentities(substr($temp, 8, -2)) ?>";
		    	</script>
		    	<?php
		    	$z++;
			$j=0;
		    }
		    $j++;
	    	}
		fclose($file);
	    }
	}
	fclose($file_lang);
	?>
	<tr>
	    <td></td>
	    <td style="text-align:center">
		<a href="<?php echo $this->url('admin', ['action' => 'add-language']) ?>"><span name='language' class='btn btn-success'><?= $this->translate('__add_a_translation') ?></span></a>
	        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<?= $this->formSubmit($form->get('submit_all')) ?>
	    </td>
	    <td></td>
	    <td></td>
	</tr>
    </table>

    <?= $this->form()->closeTag() ?>
</div>
