<?php use Zend\Form\Element; use Zend\Form\Form;

$title = $this->translate('__languages');
$this->headTitle($title);

// Creation of translation form-text
$translation = new Element\Text('translation');
$submit = new Element\Submit('Submit');
$select = new Element\Select('Select');
$translation->setAttribute('class','form-control');
$submit->setAttribute('class','btn btn-success');

$form = new Form('my-form');

?>

<div class="row">

    <span style="float:right"><?= $this->translate('__add_a_language') ?>
    <?= $this->formSelect($select->setName('select_language')->setValueOptions(['0' => 'test', '1' => 'test2', '2' => 'test3'])) ?>
    <?= $this->formSubmit($submit->setName('add_language')->setValue($this->translate('__add'))) ?></span>

    <h2><?= $this->translate('__languages') ?>&nbsp;&nbsp;
    <a href="<?php echo $this->url('diagnostic', ['action' => 'language', 'id' => 1]); ?>">
    	<button type="submit" name="language" value="fr"
            class="btn-default btn-blue btn-sm <?php echo $frClass ?>"><span
            class="text-uppercase"><span class="flag-icon flag-icon-fr"></span>&nbsp;&nbsp;fr</span>
        </button>
    </a>
    <a href="<?php echo $this->url('diagnostic', ['action' => 'language', 'id' => 2]); ?>">
        <button type="submit" name="language" value="en"
            class="btn-default btn-blue btn-sm <?php echo $enClass ?>"><span
            class="text-uppercase"><span class="flag-icon flag-icon-gb"></span>&nbsp;&nbsp;en</span>
        </button>
    </a>
    </h2>
    <br />
    <br />

    <?= $this->form()->openTag($form) ?>

    <table class="table table-responsive">

	<tr>
            <th style="text-align: center"><?= $this->translate('__translation_key'); ?></th>
            <th style="text-align: center;"><?= $this->translate('__translation'); ?></th>
	    <th style="text-align: center;"><?= $this->translate('__translation_ref'); ?> &nbsp; <?= $this->formSelect($select->setName('select_language_ref')->setValueOptions(['0' => 'fr', '1' => 'en', '2' => 'de'])) ?> &nbsp; <?= $this->formSubmit($submit->setName('change_language_ref')->setValue($this->translate('Ok'))) ?></th>
	    <th style="text-align: center;"><?= $this->translate('__action'); ?></th>
        </tr>

	<?php

	$i = 3; $j = 2; $k = 1;

	if ($this->plugin('translate')->getTranslator()->getLocale() == 'fr') {
	$_SESSION['lang'] = 1;
	$file = fopen("/var/www/diagnostic/language/fr.po", "r");
	fseek($file, 6963); // Go to the first msgid in the po file
	while (!feof($file)) {
	    $temp = fgets($file, 4096);
   	    if($i==3){echo "<tr><td class=col-lg-2 style=text-align:center>"; echo $_SESSION['key_fr'][$k]=substr($temp, 7, -2); echo "</td><td class=col-lg-5>"; $i=0;}
	    if($j==3){echo $this->formText($translation->setName('translation'.$k)->setValue(substr($temp, 8, -2))); $j=0; echo '</td><td style=text-align:center; class=col-lg-3>';
		if ($_SESSION["change_language"] == "fr") {
		    echo substr($temp, 8, -2);
		}
		else {
		}
	    echo '</td><td style=text-align:center>'; echo $this->formSubmit($submit->setName('mod'.$k)->setValue($this->translate('__modify'))); echo "&nbsp;&nbsp;"; echo $this->formSubmit($submit->setName('del'.$k)->setValue($this->translate('__delete'))); echo "</td></div></tr>"; $k++;}
	    $i++;
	    $j++;
	}
	fclose($file);
	}

	if ($this->plugin('translate')->getTranslator()->getLocale() == 'en') {
	$_SESSION['lang'] = 2;
	$file = fopen("/var/www/diagnostic/language/en.po", "r");
	fseek($file, 6281); // Go to the first msgid in the po file
	while (!feof($file)) {
	    $temp = fgets($file, 4096);
   	    if($i==3){echo "<tr><td class=col-lg-3 style=text-align:center>"; echo $_SESSION['key_fr'][$k]=substr($temp, 7, -2); echo "</td><td class=col-lg-12>"; $i=0;}
	    if($j==3){echo $this->formText($translation->setName('translation'.$k)->setValue(substr($temp, 8, -2))); $j=0; echo '</td><td>'; echo $this->formSubmit($submit->setName('mod'.$k)->setValue($this->translate('__modify'))); echo '</td><td>'; echo $this->formSubmit($submit->setName('del'.$k)->setValue($this->translate('__delete'))); echo "</td></div></tr>"; $k++;}
	    $i++;
	    $j++;
	}
	fclose($file);
	}
	?>
    </table>
    <?= $this->form()->closeTag() ?>
</div>
