<?php use Zend\Form\Element;

$title = $this->translate('__diagnostic');
$this->headTitle($title);

// Creation of translations form-text, with session value which indicate the current value
$translation_fr = new Element\Text('translation_fr');
$translation_en = new Element\Text('translation_en');
$translation_de = new Element\Text('translation_de');
$translation_fr->setValue($_SESSION['value_fr']);
$translation_fr->setAttribute('class','form-control');
$translation_en->setValue($_SESSION['value_en']);
$translation_en->setAttribute('class','form-control');
$translation_de->setValue($_SESSION['value_de']);
$translation_de->setAttribute('class','form-control');

$form->setAttribute('action', $this->url('admin', ['action' => 'modify-category', 'id' => $id]));
$form->prepare();
?>
<div class="row">
    <div class="col-lg-3 text-center"></div>
    <div class="col-lg-6 text-left">
        <h2><?= $this->translate('__modify_category') ?></h2>
        <br/>
        <?= $this->form()->openTag($form) ?>
        <table class="table table-responsive table-borderless">
            <tr>
                <td><label><?= $this->translate($form->get('translation_key')->getLabel()) ?></label></td>
                <td>
                    <?= $this->formText($form->get('translation_key')) ?>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <?= $this->formElementErrors($form->get('translation_key'), ['class' => 'bg-danger']) ?>
                    <!-- // Display error if the translation key already exist -->
                    <?php if($_SESSION['erreur_exist'] == 1){ echo "<ul class='bg-danger'> <li>" . $this->translate('__error_exist'). "</li></ul>"; } ?>
                </td>
            </tr>
            <!-- // Translations label and form-text -->
             <tr>
                <td><label><?= $this->translate('__translation') ?></label>&nbsp;<span class="flag-icon flag-icon-fr"></span></td>
                <td>
                    <?= $this->formText($translation_fr) ?>
                </td>
            </tr>
	    <tr>
                <td><label><?= $this->translate('__translation') ?></label>&nbsp;<span class="flag-icon flag-icon-gb"></span></td>
                <td>
                    <?= $this->formText($translation_en) ?>
                </td>
            </tr>
            <tr>
                <td><label><?= $this->translate('__translation') ?></label>&nbsp;<span class="flag-icon flag-icon-de"></span></td>
                <td>
                    <?= $this->formText($translation_de) ?>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <?= $this->formSubmit($form->get('submit')) ?>
                </td>
            </tr>
        </table>
        <?= $this->formHidden($form->get('csrf')) ?>
        <?= $this->form()->closeTag() ?>
    </div>
    <div class="col-lg-3 text-center"></div>
</div>
