<?php use Zend\Form\Element;

$title = $this->translate('__question');
$this->headTitle($title);

$form->setAttribute('action', $this->url('admin', ['action' => 'modify-question', 'id' => $id]));
$form->prepare();
?>
<div class="row">
    <div class="col-lg-3 text-center"></div>
    <div class="col-lg-6 text-left">
        <h2><?= $this->translate('__modify_question') ?></h2>
        <br />

        <?= $this->form()->openTag($form) ?>

        <table class="table table-responsive table-borderless">
            <tr>
                <td><label><?= $this->translate($form->get('translation_key')->getLabel()) ?></label></td>
                <td>
                    <?= $this->formText($form->get('translation_key')->setAttributes(['readonly' => 'true', 'style' => 'pointer-events: none'])) ?>
                </td>
            </tr>

            <!-- // Translation labels and form-text -->
            <?php
            $location_lang = '/var/www/diagnostic/language/languages.txt';
            $file_lang = fopen($location_lang, 'r');
            for($i=1; $i<$_SESSION['nb_lang']; $i++) {
                $temp_lang = substr(fgets($file_lang, 4096), 0, - 1);

                // Creation translation form
                $translation = new Element('translation_' . $temp_lang); // substr is for deleting the /n
                $translation->setLabel('__translation');
                $translation->setValue($_SESSION['value_' . $temp_lang]);
                $translation->setAttributes([
                    'type'  => 'text',
                    'class' => 'form-control'
                ]);
                $form->add($translation);

                // Creation help form
                $help = new Element('help_' . $temp_lang);
                $help->setLabel('__help');
                $help->setValue($_SESSION['value_' . $temp_lang . '_help']);
                $help->setAttributes([
                    'type'  => 'text',
                    'class' => 'form-control'
                ]);
                $form->add($help);
                ?>
                <tr>
                    <td><label><?= $this->translate($form->get('translation_' . $temp_lang)->getLabel()) ?></label>&nbsp;<span class="flag-icon flag-icon-<?= $temp_lang ?>"></span></td>
                    <td>
                        <?= $this->formText($form->get('translation_' . $temp_lang)) ?>
                    </td>
                </tr>
                <tr>
                    <td><label><?= $this->translate($form->get('help_' . $temp_lang)->getLabel()) ?></label>&nbsp;<span class="flag-icon flag-icon-<?= $temp_lang ?>"></span></td>
                    <td>
                        <?= $this->formText($form->get('help_' . $temp_lang)) ?>
                    </td>
                </tr>
            <?php
            }
            fclose($file_lang);
            ?>
            <tr>
                <td><label><?= $this->translate($form->get('category_id')->getLabel()) ?></label></td>
                <td>
                    <?= $this->formSelect($form->get('category_id')) ?>
                </td>
            </tr>
            <tr>
                <td><label><?= $this->translate('__threshold_max') ?></label></td>
                <td>
                    <label><?= $this->translate($form->get('threat')->getLabel()) ?></label>
                    <?= $this->formSelect($form->get('threat')) ?>
                    &nbsp; X &nbsp;
                    <label><?= $this->translate($form->get('weight')->getLabel()) ?></label>
                    <?= $this->formSelect($form->get('weight')) ?>
                </td>
            </tr>
            <tr>
                <td><label><?= $this->translate('__blocking') ?></label></td>
                <td>
                    <?= $this->formCheckbox($form->get('blocking')) ?>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <?= $this->formElementErrors($form->get('category_id'), ['class' => 'bg-danger']) ?>
                    <?= $this->formElementErrors($form->get('threat'), ['class' => 'bg-danger']) ?>
                    <?= $this->formElementErrors($form->get('weight'), ['class' => 'bg-danger']) ?>
                    <?= $this->formElementErrors($form->get('blocking'), ['class' => 'bg-danger']) ?>
                    <?= $this->formSubmit($form->get('submit')) ?>
                </td>
            </tr>
        </table>
        <?= $this->formHidden($form->get('csrf')) ?>
        <?= $this->form()->closeTag() ?>
    </div>
    <div class="col-lg-3 text-center"></div>
</div>
