<?php use Zend\Form\Element; use Zend\Form\Form;

$title = $this->translate('__settings');
$this->headTitle($title);

$this->form->setAttribute('action', $this->url('admin', ['action' => 'settings']));
$this->form->prepare();

?>

<?= $this->form()->openTag($form) ?>

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-4">
        <h2><?= $this->translate('__settings') ?></h2>

        <br />
        <br />

        <table class="table">
            <tr>
                <th style="text-align: center"><?= $this->translate('__settings'); ?></th>
                <th style="text-align: center"><?= $this->translate('__action'); ?></th>
            </tr>

            <tr>
                <td style="text-align: center;"><?= $this->translate($form->get('select_language')->getLabel()); ?></td>
                <td><?= $this->formSelect($form->get('select_language')) ?></td>
            </tr>

            <tr>
                <td style="text-align: center;"><?= $this->translate($form->get('checkbox_mxCheck')->getLabel()); ?></td>
                <td style="text-align: center;"><?= $this->formCheckbox($form->get('checkbox_mxCheck')) ?></td>
            </tr>

            <tr>
                <td style="text-align: center;"><?= $this->translate($form->get('encryption_key')->getLabel()); ?></td>
                <td><?= $this->formText($form->get('encryption_key')) ?></td>
            </tr>
            <tr>
                <td>
                    <?php if($success_upload == 1){ echo "<ul class='bg-success'> <li>" . $this->translate('__success_file'). "</li></ul>"; } ?>
                </td>
            </tr>
        </table>
        <span style='float:right'><?= $this->formSubmit($form->get('submit')) ?></span>
     </div>
</div>

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-5">
        <h2><?= $this->translate('__statistics') ?></h2>

        <br />
        <br />

        <table class="table">
            <tr>
                <th style="text-align: center"><?= $this->translate('Date'); ?></th>
                <th style="text-align: center"><?= $this->translate('__activity'); ?></th>
                <th style="text-align: center"><?= $this->translate('__action'); ?></th>
                <th style="text-align: center"><?= $this->translate('__record'); ?></th>
            </tr>

            <tr>
                <td class="col-lg-2"><?= $this->formSelect($form->get('date')) ?></td>
                <td class="col-lg-7"><?= $this->formSelect($form->get('activity')) ?></td>
                <td class="col-lg-1"><?= $this->formText($form->get('diagnosis_stat')) ?></td>
                <td class="col-lg-2" style="text-align: center;"><?= $this->formSubmit($form->get('submit_stat')) ?></td>
            </tr>

            <tr>
                <td></td>
                <td>
                    <?php if($error_res == 1){ echo "<ul class='bg-danger'> <li>" . $this->translate('__error_res'). "</li></ul>"; } ?>
                    <?php if($success_upload2 == 1){ echo "<ul class='bg-success'> <li>" . $this->translate('__success_file'). "</li></ul>"; } ?>
                </td>
            </tr>
        </table>
     </div>
</div>

<?= $this->form()->closeTag() ?>
